### ISSUE TITLE
TestExpressionArray::test_divide_scalar_array fails on i586

### ISSUE THREAD

**Issue by mcepl** [XanaduAI/blackbird#42] opened 2021-05-12 13:32 UTC
When running the packaging scripts for openSUSE package of python-quantum-blackbird I get this failure in the test suite:
```
[   26s] + PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-quantum-blackbird-0.3.0-0.i386/usr/lib/python3.9/site-packages
[   26s] + PYTHONDONTWRITEBYTECODE=1
[   26s] + pytest-3.9 --ignore=_build. --ignore=_build.python39 --ignore=_build.python38 -v
[   27s] ============================= test session starts ==============================
[   27s] platform linux -- Python 3.9.4, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python3.9
[   27s] cachedir: .pytest_cache
[   27s] rootdir: /home/abuild/rpmbuild/BUILD/blackbird-0.3.0
[   28s] collecting ... collected 490 items
[   28s]
[ ... plenty of passing tests removed from the report ...]
[   30s]
[   30s] =================================== FAILURES ===================================
[   30s] ______________ TestExpressionArray.test_divide_scalar_array[n10] _______________
[   30s]
[   30s] self = <test_auxiliary.TestExpressionArray object at 0xf42bd5f8>
[   30s] parser = <blackbird.blackbirdParser.blackbirdParser object at 0xf42976a0>
[   30s] ctx = <antlr4.ParserRuleContext.ParserRuleContext object at 0xf429f358>
[   30s] n1 = ('0+5j', 5j), num = <function num.<locals>._number_label at 0xf4297a48>
[   30s] var = <function var.<locals>._var_label at 0xf4297538>
[   30s] monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0xf42e3838>
[   30s]
[   30s]     @pytest.mark.parametrize('n1', test_complex)
[   30s]     def test_divide_scalar_array(self, parser, ctx, n1, num, var, monkeypatch):
[   30s]         """Test division of a number and an array"""
[   30s]
[   30s]         class DummyMulLabel(blackbirdParser.MulLabelContext):
[   30s]             """Dummy mul label"""
[   30s]             expression = lambda self: (num(n1[0]), var("U"))
[   30s]
[   30s]         with monkeypatch.context() as m:
[   30s]             m.setattr(blackbird.auxiliary, "_VAR", {"U": U})
[   30s]
[   30s]             expr = DummyMulLabel(parser, ctx)
[   30s]             expr.DIVIDE = lambda: True
[   30s] >           assert np.all(_expression(expr) == n1[1]/U)
[   30s] E           AssertionError: assert False
[   30s] E            +  where False = <function all at 0xf6a7b658>(array([[0.  +...0.j        ]]) == array([[ 0.  ...0.j        ]])
[   30s] E            +    where <function all at 0xf6a7b658> = np.all
[   30s] E               +array([[0.  +1.66666667j, 0.  +2.5j       ],\n
[   30s] E               +       [2.5 +2.5j       , 0. -10.j        ]])
[   30s] E               -array([[ 0.  +1.66666667j,  0.  +2.5j       ],\n
[   30s] E               -       [ 2.5 +2.5j       , -0. -10.j        ]])
[   30s] E               Full diff:
[   30s] E               - array([[ 0.  +1.66666667j,  0.  +2.5j       ],
[   30s] E               ?         -                  -...
[   30s] E
[   30s] E               ...Full output truncated (6 lines hidden), use '-vv' to show)
[   30s]
[   30s] blackbird_python/blackbird/tests/test_auxiliary.py:612: AssertionError
[   30s] ---------------------------- Captured stdout setup -----------------------------
[   30s] ANTLR runtime and generated code versions disagree: 4.9.1!=4.8
[   30s] ______________ TestExpressionArray.test_divide_scalar_array[n12] _______________
[   30s]
[   30s] self = <test_auxiliary.TestExpressionArray object at 0xf4325340>
[   30s] parser = <blackbird.blackbirdParser.blackbirdParser object at 0xf42ff7c0>
[   30s] ctx = <antlr4.ParserRuleContext.ParserRuleContext object at 0xf429fe98>
[   30s] n1 = ('0.54+0.21j', (0.54+0.21j))
[   30s] num = <function num.<locals>._number_label at 0xf42ff2b0>
[   30s] var = <function var.<locals>._var_label at 0xf42ffbb0>
[   30s] monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0xf42bda48>
[   30s]
[   30s]     @pytest.mark.parametrize('n1', test_complex)
[   30s]     def test_divide_scalar_array(self, parser, ctx, n1, num, var, monkeypatch):
[   30s]         """Test division of a number and an array"""
[   30s]
[   30s]         class DummyMulLabel(blackbirdParser.MulLabelContext):
[   30s]             """Dummy mul label"""
[   30s]             expression = lambda self: (num(n1[0]), var("U"))
[   30s]
[   30s]         with monkeypatch.context() as m:
[   30s]             m.setattr(blackbird.auxiliary, "_VAR", {"U": U})
[   30s]
[   30s]             expr = DummyMulLabel(parser, ctx)
[   30s]             expr.DIVIDE = lambda: True
[   30s] >           assert np.all(_expression(expr) == n1[1]/U)
[   30s] E           AssertionError: assert False
[   30s] E            +  where False = <function all at 0xf6a7b658>(array([[ 0.18....08 -0.42j ]]) == array([[ 0.18....08 -0.42j ]])
[   30s] E            +    where <function all at 0xf6a7b658> = np.all
[   30s] E               +array([[ 0.18 +0.07j ,  0.27 +0.105j],\n
[   30s] E               +       [ 0.375-0.165j, -1.08 -0.42j ]])
[   30s] E               -array([[ 0.18 +0.07j ,  0.27 +0.105j],\n
[   30s] E               -       [ 0.375-0.165j, -1.08 -0.42j ]])
[   30s] E               Full diff:
[   30s] E                 array([[ 0.18 +0.07j ,  0.27 +0.105j],
[   30s] E                        [ 0.375-0.165j, -1.08 -0.42j ]],...
[   30s] E
[   30s] E               ...Full output truncated (2 lines hidden), use '-vv' to show)
[   30s]
[   30s] blackbird_python/blackbird/tests/test_auxiliary.py:612: AssertionError
[   30s] ---------------------------- Captured stdout setup -----------------------------
[   30s] ANTLR runtime and generated code versions disagree: 4.9.1!=4.8
[   30s] =============================== warnings summary ===============================
[   30s] ../../BUILDROOT/python-quantum-blackbird-0.3.0-0.i386/usr/lib/python3.9/site-packages/blackbird/listener.py:78
[   30s]   /home/abuild/rpmbuild/BUILDROOT/python-quantum-blackbird-0.3.0-0.i386/usr/lib/python3.9/site-packages/blackbird/listener.py:78: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
[   30s]   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
[   30s]     "str": np.str,
[   30s]
[   30s] ../../BUILDROOT/python-quantum-blackbird-0.3.0-0.i386/usr/lib/python3.9/site-packages/blackbird/listener.py:79
[   30s]   /home/abuild/rpmbuild/BUILDROOT/python-quantum-blackbird-0.3.0-0.i386/usr/lib/python3.9/site-packages/blackbird/listener.py:79: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
[   30s]   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
[   30s]     "bool": np.bool,
[   30s]
[   30s] blackbird_python/blackbird/tests/test_auxiliary.py: 20 warnings
[   30s] blackbird_python/blackbird/tests/test_listener.py: 1 warning
[   30s]   /usr/lib/python3.9/site-packages/numpy/core/fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
[   30s]     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
[   30s]
[   30s] blackbird_python/blackbird/tests/test_listener.py::TestParsingMetadata::test_type_kwarg
[   30s]   /home/abuild/rpmbuild/BUILDROOT/python-quantum-blackbird-0.3.0-0.i386/usr/lib/python3.9/site-packages/blackbird/listener.py:179: SyntaxWarning: Target devices only accept keyword options of the form option=value. All positional arguments without a named option will be ignored.
[   30s]     warnings.warn(
[   30s]
[   30s] -- Docs: https://docs.pytest.org/en/stable/warnings.html
[   30s] =========================== short test summary info ============================
[   30s] FAILED blackbird_python/blackbird/tests/test_auxiliary.py::TestExpressionArray::test_divide_scalar_array[n10]
[   30s] FAILED blackbird_python/blackbird/tests/test_auxiliary.py::TestExpressionArray::test_divide_scalar_array[n12]
[   30s] ============ 2 failed, 483 passed, 5 skipped, 24 warnings in 2.95s =============
```
Complete [log](https://github.com/XanaduAI/blackbird/files/6466474/_log.txt) with all details.

**Comment by thisac** [comment] 2021-05-12 20:39
Hi @mcepl. Thank you for posting this issue. Could you provide some more details on how you're installing the Blackbird package. If I understand it correctly, you've grabbed it from OpenSUSE, running the tests that are included there. Is this correct?

I noticed that you've pushed a commit referencing this issue to bmwiedemann/openSUSE, seemingly just skipping the tests on 32bit systems. Is everything else working fine apart from this?

**Comment by mcepl** [comment] 2021-05-12 21:03
No, I am building the package for openSUSE. You have attached complete log of all packages used. You see that everything else is working just fine.

**Comment by thisac** [comment] 2021-05-14 14:41
I understand. Unfortunately, we cannot guarantee that the package will work fully on all systems (in this case, there seem to be issues with running the tests on i586 processors). If you could provide more details of your Python environment, e.g. what packages are installed as well as your operating system, we could test it out a bit more, although if the issue is related to i586 I'm afraid this might be something that we cannot guarantee will work.

**Comment by mcepl** [comment] 2021-05-14 15:16
> If you could provide more details of your Python environment, e.g. what packages are installed as well as your operating system, we could test it out a bit more,

What part of https://github.com/XanaduAI/blackbird/files/6466474/_log.txt you don't understand?

`openSUSE_Tumbleweed-i586`

```
$ curl -L -s https://github.com/XanaduAI/blackbird/files/6466474/_log.txt|grep '\] python'
[    9s] python38-base-3.8.9-1.2               ########################################
[    9s] python39-base-3.9.4-1.3               ########################################
[    9s] python39-six-1.15.0-2.3               ########################################
[   10s] python38-six-1.15.0-2.3               ########################################
[   10s] python39-iniconfig-1.1.1-1.3          ########################################
[   10s] python39-pyparsing-2.4.7-2.6          ########################################
[   10s] python39-packaging-20.9-1.2           ########################################
[   10s] python38-iniconfig-1.1.1-1.3          ########################################
[   10s] python38-pyparsing-2.4.7-2.6          ########################################
[   10s] python38-packaging-20.9-1.2           ########################################
[   13s] python39-apipkg-1.5-4.3               ########################################
[   13s] python39-py-1.10.0-1.3                ########################################
[   13s] python39-appdirs-1.4.4-2.3            ########################################
[   13s] python39-attrs-20.3.0-1.3             ########################################
[   13s] python39-decorator-4.4.2-1.5          ########################################
[   13s] python39-more-itertools-8.7.0-1.2     ########################################
[   14s] python39-zipp-3.4.1-1.2               ########################################
[   14s] python39-importlib-metadata-3.7.2-1.1 ########################################
[   14s] python39-pluggy-0.13.1-1.6            ########################################
[   14s] python39-ordered-set-3.1.1-5.3        ########################################
[   14s] python39-setuptools-44.1.1-4.4        ########################################
[   14s] python39-toml-0.10.2-2.3              ########################################
[   14s] python39-wcwidth-0.2.5-2.3            ########################################
[   14s] python39-gmpy-1.17-4.43               ########################################
[   14s] python39-mpmath-1.2.1-9.3             ########################################
[   14s] python38-apipkg-1.5-4.3               ########################################
[   14s] python38-py-1.10.0-1.3                ########################################
[   14s] python38-appdirs-1.4.4-2.3            ########################################
[   14s] python38-attrs-20.3.0-1.3             ########################################
[   14s] python38-decorator-4.4.2-1.5          ########################################
[   14s] python38-more-itertools-8.7.0-1.2     ########################################
[   14s] python38-zipp-3.4.1-1.2               ########################################
[   14s] python38-importlib-metadata-3.7.2-1.1 ########################################
[   14s] python38-pluggy-0.13.1-1.6            ########################################
[   14s] python38-ordered-set-3.1.1-5.3        ########################################
[   14s] python38-setuptools-44.1.1-4.4        ########################################
[   14s] python38-toml-0.10.2-2.3              ########################################
[   14s] python38-wcwidth-0.2.5-2.3            ########################################
[   14s] python38-gmpy-1.17-4.43               ########################################
[   14s] python38-mpmath-1.2.1-9.3             ########################################
[   18s] python38-numpy-1.20.2-90.1            ########################################
[   18s] python39-numpy-1.20.2-90.1            ########################################
[   19s] python-rpm-macros-20210204.937b8d8-1.6########################################
[   22s] python39-sympy-1.7.1-21.35            ########################################
[   23s] python38-sympy-1.7.1-21.35            ########################################
[   23s] python38-pytest-6.2.2-1.3             ########################################
[   23s] python38-networkx-2.5-47.6            ########################################
[   23s] python39-pytest-6.2.2-1.3             ########################################
[   23s] python39-networkx-2.5-47.6            ########################################
[   24s] python39-antlr4-python3-runtime-4.9.1-########################################
[   24s] python38-antlr4-python3-runtime-4.9.1-########################################
python-fastcluster@stitny$
```

**Comment by josh146** [comment] 2021-05-14 15:23
Hi @mcepl! As @thisac mentions above, unfortunately we do not provide support for i586 builds/architectures; our tests and code is currently written only with x86_64 in mind.

If you find the reason why the tests are failing on i586, feel free to contribute a PR back! While we aren't actively supporting i586, external contributions that add support for additional architectures would be most welcomed.

**Comment by mcepl** [comment] 2021-05-14 15:26
It's funny, because `setarch` is part of every `util-linux` package, but whatever.

**Comment by thisac** [comment] 2021-05-19 14:56
Hi @mcepl. Unfortunately, since we aren't actively supporting i586, I will be closing this issue. Hopefully everything works fine on 64bit systems, but don't hesitate to open another issue if you find that something isn't working as it should.

**Closed by thisac** 2021-05-19 14:56 UTC
